@MathTutor.Api_HostAddress = http://localhost:5132

### Start a new session
POST {{MathTutor.Api_HostAddress}}/api/session/start
Content-Type: application/json

{
  "numberOfQuestions": 10
}

###

### Get next question for a session
GET {{MathTutor.Api_HostAddress}}/api/session/{{sessionId}}/next
Accept: application/json

###

### Submit an answer for a question
POST {{MathTutor.Api_HostAddress}}/api/session/{{sessionId}}/answer
Content-Type: application/json

{
  "id": 1,
  "answer": 8
}

###

### Get session summary
GET {{MathTutor.Api_HostAddress}}/api/session/{{sessionId}}/summary
Accept: application/json

###
